### ISSUE TITLE
Open bus reads

### ISSUE THREAD

**Issue by dspiteri** [MiSTer-devel/C16_MiSTer#12]
Hi this open bus reads as implemented on the MIST core fixes a bug with Giana Sisters. Any chance to implement?  Thanks!

https://masto.ai/@mistboard/112223359333458765

**Comment by sorgelig** [comment]
try this build:
[C16_t1.zip](https://github.com/user-attachments/files/16981946/C16_t1.zip)

**Comment by sorgelig** [comment]
Strange.. Make sure Main is up to date.

**Comment by niallquinn71** [comment]
Splendid, many thanks @sorgelig !
