### ISSUE TITLE
Adventure Park doesn't load

### ISSUE THREAD

**Issue by Dion-Guy** [MiSTer-devel/C16_MiSTer#4]
New 2019 game Adventure Park doesn't load, just goes to a black screen.

http://plus4world.powweb.com/software/Adventure_Park

**Comment by PhantombrainM** [comment]
It has already been fixed in source code and will work with next release.

**Comment by Dion-Guy** [comment]
> It has already been fixed in source code and will work with next release.

That’s great news; thanks for letting me know.

**Comment by Dion-Guy** [comment]
> It has already been fixed in source code and will work with next release.

That’s great; thanks for letting me know.
