### ISSUE TITLE
Strawberry Fields - corrupt graphics

### ISSUE THREAD

**Issue by chris-y** [MiSTer-devel/C16_MiSTer#7]
I'm using this download for testing (I have a second different download which does the same thing): http://plus4world.powweb.com/dl/games/s/strawberry_fields.prg

Strawberry Fields is supposed to look like this (screenshot from VICE):
![image](https://user-images.githubusercontent.com/1818803/125970878-20babdfb-143f-43f2-aa9f-1f66c263b4a8.png)

On the MiSTer it is displaying like this:
![image](https://user-images.githubusercontent.com/1818803/125971188-52db9821-7ef3-48da-b1ea-30b95f66d935.png)

I'm not seeing issues with other games so it appears to be something to do with this game rather than my config.

**Comment by sorgelig** [comment]
cannot confirm.
I have the same picture on my MiSTer as from VICE.

**Comment by chris-y** [comment]
I just tried it again and it is working now!  Odd.
