### ISSUE TITLE
SID + TED music out of tune

### ISSUE THREAD

**Issue by WebbedQuasar** [MiSTer-devel/C16_MiSTer#8]
Please watch this video (and read the comments): https://youtu.be/vl3oMTk3a44
The music is out of tune here in Tetris 2K21. The developer of this game implemented TED only, SID + TED, AY + TED. With TED alone, you only hear the bass (normal in this case). As soon as you activate the SID like in the video, the music is out of tune.
Perhaps one could implement a SID only mode, or solve the problem in some other way, so that SID + TED harmonize correctly with each other?

**Comment by sorgelig** [comment]
why you closed it? Is it got fixed in game code?

**Comment by WebbedQuasar** [comment]
Since all the YT videos of this game sound exactly the same, I'm pretty sure this isn't a bug of this core. Also, I've never had sound issues with Plus/4 games that support the SID chip.
However, any C16 / Plus/4 - core updates are always welcome (how about spinner (paddle) support?).

**Comment by sorgelig** [comment]
Which game uses paddle?

**Comment by WebbedQuasar** [comment]
The only game I'm aware of is this fantastic conversion of Arkanoid: https://plus4world.powweb.com/software/Arkanoid_Plus4_Analogue_Edition
Personally, I'd appreciate paddle support for the VIC-20 core even more, for example for the paddle version of the game "Clowns". But I can also live without paddle support on both cores. I'm just thinking out loud, if it's worth the effort, you have to decide.
