### ISSUE TITLE
boot.rom not loaded and option greyed out in GUI

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/C16_MiSTer#9]
Last two releases broke loading boot.rom and it's greyed out in GUI.

I think it's commit 0e36f3f6d61c8e554e4e8aed363c550dfb30719e
Line 215++

If I rename boot.rom (it's not visible by GUI when Load *.ROM in GUI is selected) it becomes visible and it works.

Wiki refers to boot.romin C16 folder

**Comment by sorgelig** [comment]
wiki needs to be updated. Better to name it as Kernal.rom and load through OSD.
You may have several Kernals.

**Comment by PhantombrainM** [comment]
I updated the wiki and made a PR
